### PR TITLE
Update edit.php

### PR DESCRIPTION
**Pull request by blacknon**

### CODE REVIEW

**Comment by hcaz** [comment]
I just checked this on my local install, this fixes any issues editing domains and SSL certificates for me.

**Comment by chetcuti** [comment]
Was the below code causing either of you issues when editing a domain?

Change 3a55fb2e0790c1b76aca39d00fbf919692ac2f8c

`$subtext = '[<a target="_blank" href="notes.php?did=' . htmlentities($did, ENT_QUOTES) . '">view full notes</a>]';`

I'm just curious why it was commented out.

**Comment by hcaz** [comment]
It wasn't causing issues for me, so I am not sure why it was commented out. Since its only a link it could probably be left in without any harm to the actual system

**Comment by chetcuti** [comment]
@blacknon, thanks for reporting ed5b0c6b032be48372384269913772a06c7e02f7! I have absolutely no idea how the order got that messed up.

**Pull request merged**
